# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8765ad60bfda7395e1b7ac0e56be4028776090b4846728fa1c188f7dc2aec5d0eef92439786a7835cec297c7322c3abc935dd448b26dd9056713a56eddf696b6

test:
  secret_key_base: 71051340ef1f4ba81d4650228ad1aa91db4d9681f066974b86eabd4c7d13aba6baf04de6d0bd9040623df46204dfbdb2026721a6628125daa1f604f38a24350c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
